shell.run("wget", "run", "https://github.com/MichielP1807/more-fonts/raw/main/installer.lua")
shell.run("wget", "https://github.com/Volpe42/stargate-monitors/raw/main/sgc-monitors.lua")
shell.run("wget", "https://github.com/Volpe42/stargate-monitors/raw/main//fonts/mw720")
shell.run("wget", "https://github.com/Volpe42/stargate-monitors/raw/main/fonts/mw720s")
shell.run("wget", "https://github.com/Volpe42/stargate-monitors/raw/main/fonts/mw1280")
